### ISSUE TITLE
Dank Tech dont work

### ISSUE THREAD

**Issue by Sventt** [Sefiraat/DankTech#4]
## I don't know

Asgard Slimefun Server 1.16.5 version

**Comment by Sventt** [comment]
My Discord is Sventt#6042

**Comment by Sventt** [comment]
Also I would like to know if I need to have installed other dependency , I have slimefun, and the jar of danktech

**Comment by Sefiraat** [comment]
I sventt,

I did drop you a message in discord but I think I may have found this issue while awaiting a reply. Please try with version 1.2.1.
If you still have the issue afterwards, follow the instructions I left in discord so I can look further into this :)

Let me know if this works, ill close this issue in a few days if I dont hear from you

**Comment by Sefiraat** [comment]
This issue was caused due to a conflict with a crafting plugin. I have added a work around that will allow Shallow Danks to be converted to a real dank when right clicked. This will also allow /sf cheat to work which is a bonus!

I will close this issue and you have the snapshot jar on discord to test the solution before I release the next version :)
